# Generated by Django 3.1.7 on 2021-04-09 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210409_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 18, 4, 7, 994619, tzinfo=utc)),
        ),
    ]
